pygments: false
lsi: false

url: /documentation

exclude:
  - README.md
  - CNAME
  - TODO.md
  - script
  - Procfile
  - Gemfile
  - Gemfile.lock
  - LICENSE-CC-BY.textile
  - cmd.lnk
timezone: Europe/Berlin

github_repo: https://github.com/learnweb/documentation
github_git: git://github.com/learnweb/documentation.git

moodle_name: Learnweb
moodle_url: https://www.uni-muenster.de/LearnWeb
moodle_sso: https://sso.uni-muenster.de/LearnWeb
moodle_version: 24

university_name: Westf채lische Wilhelms-Universit채t M체nster
university_name_short: WWU M체nster

chapters:
- einleitung
- kurs grundlagen
- dateiverwaltung
